using com.mindrocks.text.Parser;
using com.mindrocks.macros.LazyMacro;

class MekTokens {
	static var spaceP = ' '.identifier().lazyF();
	static var tabP   = '\t'.identifier().lazyF();
	static var retP   = '\r'.identifier().lazyF();
	static var nlnP   = '\n'.identifier().lazyF();

	static var identifierR = ~/'(.+)'/;
	static var numberR     = ~/[-+]?[0-9]*\.?[0-9]+/;
	static var commentR    = ~/=.*/;

	static public var spacingP = [
		spaceP,
		tabP,
		retP,
		nlnP,
		commentR.regexParser(),
	].ors().many().lazyF();

	static function s<T>(p: Void -> Parser<String, T>): Void -> Parser<String, T> {
		return p.and_(spacingP);
	}

	static public var identifierP = s(identifierR.regexParser()).tag('identifier').lazyF();
	static public var numberP     = s(numberR.regexParser()).tag('number').lazyF();

	static public var percentT           = s('%'.identifier());
	static public var dashT              = s('-'.identifier());
	static public var slashT             = s('/'.identifier());
	static public var colonT             = s(':'.identifier());
	static public var quoteT             = s('\''.identifier());
	static public var abilityT           = s('Ability'.identifier());
	static public var ablativeT          = s('Ablative'.identifier());
	static public var accuracyT          = s('Accuracy'.identifier());
	static public var activeT            = s('Active'.identifier());
	static public var addedT             = s('Added'.identifier());
	static public var advancedT          = s('Advanced'.identifier());
	static public var allPurposeT        = s('All-Purpose'.identifier());
	static public var alphaT             = s('Alpha'.identifier());
	static public var ammoT              = s('Ammo'.identifier());
	static public var analyzerT          = s('Analyzer'.identifier());
	static public var angleT             = s('Angle'.identifier());
	static public var antiMissileT       = s('Anti-Missile'.identifier());
	static public var antiPersonnelT     = s('Anti-Personnel'.identifier());
	static public var antiTheftT         = s('Anti-Theft'.identifier());
	static public var armT               = s('Arm'.identifier());
	static public var armorT             = s('Armor'.identifier());
	static public var armorPiercingT     = s('Armor-Piercing'.identifier());
	static public var armoredT           = s('Armored'.identifier());
	static public var attackT            = s('Attack'.identifier());
	static public var batteryT           = s('Battery'.identifier());
	static public var beamT              = s('Beam'.identifier());
	static public var beamingT           = s('Beaming'.identifier());
	static public var betaT              = s('Beta'.identifier());
	static public var binderT            = s('Binder'.identifier());
	static public var blastT             = s('Blast'.identifier());
	static public var boggSprayT         = s('Bogg-Spray'.identifier());
	static public var burstT             = s('Burst'.identifier());
	static public var changeT            = s('Change'.identifier());
	static public var clipFedT           = s('Clip-Fed'.identifier());
	static public var clumsyT            = s('Clumsy'.identifier());
	static public var cockpitT           = s('Cockpit'.identifier());
	static public var codeT              = s('Code'.identifier());
	static public var commT              = s('Comm'.identifier());
	static public var controlT           = s('Control'.identifier());
	static public var costT              = s('Cost'.identifier());
	static public var countermissileT    = s('Countermissile'.identifier());
	static public var crewT              = s('Crew'.identifier());
	static public var damageT            = s('Damage'.identifier());
	static public var defenseT           = s('Defense'.identifier());
	static public var disruptorT         = s('Disruptor'.identifier());
	static public var eccmT              = s('ECCM'.identifier());
	static public var ecmT               = s('ECM'.identifier());
	static public var ejectionT          = s('Ejection'.identifier());
	static public var emptyT             = s('Empty'.identifier());
	static public var enclosingT         = s('Enclosing'.identifier());
	static public var energyT            = s('Energy'.identifier());
	static public var entangleT          = s('Entangle'.identifier());
	static public var escapeT            = s('Escape'.identifier());
	static public var extraT             = s('Extra'.identifier());
	static public var factorT            = s('Factor'.identifier());
	static public var flareT             = s('Flare'.identifier());
	static public var foamT              = s('Foam'.identifier());
	static public var fragileT           = s('Fragile'.identifier());
	static public var fuseT              = s('Fuse'.identifier());
	static public var gammaT             = s('Gamma'.identifier());
	static public var gravityT           = s('Gravity'.identifier());
	static public var handT              = s('Hand'.identifier());
	static public var handyT             = s('Handy'.identifier());
	static public var headT              = s('Head'.identifier());
	static public var heavyT             = s('Heavy'.identifier());
	static public var hexT               = s('Hex'.identifier());
	static public var highExplosiveT     = s('High-Explosive'.identifier());
	static public var hydroT             = s('Hydro'.identifier());
	static public var hyperT             = s('Hyper'.identifier());
	static public var hypervelocityT     = s('Hypervelocity'.identifier());
	static public var inT                = s('In'.identifier());
	static public var incendiaryT        = s('Incendiary'.identifier());
	static public var infinityT          = s('Infinity'.identifier());
	static public var intensifiersT      = s('Intensifiers'.identifier());
	static public var interferenceT      = s('Interference'.identifier());
	static public var killsT             = s('Kills'.identifier());
	static public var kineticT           = s('Kinetic'.identifier());
	static public var kmT                = s(~/[Kk]m/.regexParser());
	static public var legT               = s('Leg'.identifier());
	static public var lensT              = s('Lens'.identifier());
	static public var liftwireT          = s('Liftwire'.identifier());
	static public var lightT             = s('Light'.identifier());
	static public var lightweightT       = s('Lightweight'.identifier());
	static public var lockT              = s('Lock'.identifier());
	static public var longT              = s('Long'.identifier());
	static public var magneticT          = s('Magnetic'.identifier());
	static public var maneuverT          = s('Maneuver'.identifier());
	static public var marineT            = s('Marine'.identifier());
	static public var matedT             = s('Mated'.identifier());
	static public var matterT            = s('Matter'.identifier());
	static public var mediumT            = s('Medium'.identifier());
	static public var mediumweightT      = s('Mediumweight'.identifier());
	static public var megaT              = s('Mega'.identifier());
	static public var megaBeamT          = s('Mega-Beam'.identifier());
	static public var mektonT            = s('Mekton'.identifier());
	static public var meleeT             = s('Melee'.identifier());
	static public var micromanipulatorsT = s('Micromanipulators'.identifier());
	static public var mirrorT            = s('Mirror'.identifier());
	static public var missileT           = s('Missile'.identifier());
	static public var moduleT            = s('Module'.identifier());
	static public var morphableT         = s('Morphable'.identifier());
	static public var mountT             = s('Mount'.identifier());
	static public var multiFeedT         = s('Multi-Feed'.identifier());
	static public var nightlightsT       = s('Nightlights'.identifier());
	static public var nuclearT           = s('Nuclear'.identifier());
	static public var offensiveT         = s('Offensive'.identifier());
	static public var onlyT              = s('Only'.identifier());
	static public var operationT         = s('Operation'.identifier());
	static public var packageT           = s('Package'.identifier());
	static public var paintballT         = s('Paintball'.identifier());
	static public var parachuteT         = s('Parachute'.identifier());
	static public var passengerT         = s('Passenger'.identifier());
	static public var phalanxT           = s('Phalanx'.identifier());
	static public var podT               = s('Pod'.identifier());
	static public var poolT              = s('Pool'.identifier());
	static public var powerT             = s('Power'.identifier());
	static public var projectileT        = s('Projectile'.identifier());
	static public var qualityT           = s('Quality'.identifier());
	static public var quickT             = s('Quick'.identifier());
	static public var radarT             = s('Radar'.identifier());
	static public var radioT             = s('Radio'.identifier());
	static public var radiusT            = s('Radius'.identifier());
	static public var ramT               = s('RAM'.identifier());
	static public var rangeT             = s('Range'.identifier());
	static public var rangedT            = s('Ranged'.identifier());
	static public var reEntryT           = s('Re-Entry'.identifier());
	static public var reactiveT          = s('Reactive'.identifier());
	static public var rechargeableT      = s('Rechargeable'.identifier());
	static public var reflectorT         = s('Reflector'.identifier());
	static public var remoteT            = s('Remote'.identifier());
	static public var resetT             = s('Reset'.identifier());
	static public var resolutionT        = s('Resolution'.identifier());
	static public var resonanceT         = s('Resonance'.identifier());
	static public var returningT         = s('Returning'.identifier());
	static public var runningT           = s('Running'.identifier());
	static public var scatterT           = s('Scatter'.identifier());
	static public var scattershotT       = s('Scattershot'.identifier());
	static public var screenT            = s('Screen'.identifier());
	static public var seatT              = s('Seat'.identifier());
	static public var sensorT            = s('Sensor'.identifier());
	static public var shieldT            = s('Shield'.identifier());
	static public var shockT             = s('Shock'.identifier());
	static public var shotsT             = s('Shots'.identifier());
	static public var silentT            = s('Silent'.identifier());
	static public var skillT             = s('Skill'.identifier());
	static public var slickSprayT        = s('Slick-Spray'.identifier());
	static public var smartT             = s('Smart'.identifier());
	static public var smokeT             = s('Smoke'.identifier());
	static public var spaceT             = s('Space'.identifier());
	static public var spotlightsT        = s('Spotlights'.identifier());
	static public var spottingT          = s('Spotting'.identifier());
	static public var standardT          = s('Standard'.identifier());
	static public var stereoT            = s('Stereo'.identifier());
	static public var stoppingT          = s('Stopping'.identifier());
	static public var storageT           = s('Storage'.identifier());
	static public var strikerT           = s('Striker'.identifier());
	static public var suiteT             = s('Suite'.identifier());
	static public var superT             = s('Super'.identifier());
	static public var superlightT        = s('Superlight'.identifier());
	static public var surgeT             = s('Surge'.identifier());
	static public var swashbucklingT     = s('Swashbuckling'.identifier());
	static public var tailT              = s('Tail'.identifier());
	static public var tanglerT           = s('Tangler'.identifier());
	static public var targetT            = s('Target'.identifier());
	static public var thrownT            = s('Thrown'.identifier());
	static public var torsoT             = s('Torso'.identifier());
	static public var tracerT            = s('Tracer'.identifier());
	static public var turnsT             = s('Turns'.identifier());
	static public var useT               = s('Use'.identifier());
	static public var valueT             = s('Value'.identifier());
	static public var variableT          = s('Variable'.identifier());
	static public var vehicleT           = s('Vehicle'.identifier());
	static public var warmUpT            = s('Warm-Up'.identifier());
	static public var wideT              = s('Wide'.identifier());
	static public var wingT              = s('Wing'.identifier());
	static public var wireControlledT    = s('Wire-Controlled'.identifier());
	static public var xT                 = s('X'.identifier());
}